// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401080225_SeedDataRefactor")]
    partial class SeedDataRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.FetusData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("HeadCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PregnancyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PregnancyId");

                    b.ToTable("FetusDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2023, 1, 1),
                            HeadCircumference = 28.0m,
                            Height = 45.0m,
                            PregnancyId = 1,
                            Weight = 3.0m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2023, 1, 8),
                            HeadCircumference = 28.4m,
                            Height = 45.8m,
                            PregnancyId = 1,
                            Weight = 3.3m
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2023, 1, 15),
                            HeadCircumference = 28.9m,
                            Height = 46.5m,
                            PregnancyId = 1,
                            Weight = 3.5m
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2023, 1, 22),
                            HeadCircumference = 29.3m,
                            Height = 47.2m,
                            PregnancyId = 1,
                            Weight = 3.7m
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2023, 1, 29),
                            HeadCircumference = 29.8m,
                            Height = 48.0m,
                            PregnancyId = 1,
                            Weight = 4.0m
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2023, 2, 5),
                            HeadCircumference = 30.2m,
                            Height = 49.0m,
                            PregnancyId = 1,
                            Weight = 4.2m
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2023, 2, 12),
                            HeadCircumference = 30.7m,
                            Height = 50.2m,
                            PregnancyId = 1,
                            Weight = 4.5m
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2023, 2, 19),
                            HeadCircumference = 31.1m,
                            Height = 51.0m,
                            PregnancyId = 1,
                            Weight = 4.7m
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2023, 2, 26),
                            HeadCircumference = 31.6m,
                            Height = 52.3m,
                            PregnancyId = 1,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2023, 3, 5),
                            HeadCircumference = 32.0m,
                            Height = 53.5m,
                            PregnancyId = 1,
                            Weight = 5.3m
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2023, 3, 12),
                            HeadCircumference = 32.6m,
                            Height = 54.8m,
                            PregnancyId = 1,
                            Weight = 5.6m
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2023, 3, 19),
                            HeadCircumference = 33.0m,
                            Height = 55.5m,
                            PregnancyId = 1,
                            Weight = 5.8m
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2023, 3, 26),
                            HeadCircumference = 33.5m,
                            Height = 56.8m,
                            PregnancyId = 1,
                            Weight = 6.1m
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2023, 4, 2),
                            HeadCircumference = 34.0m,
                            Height = 57.5m,
                            PregnancyId = 1,
                            Weight = 6.3m
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2023, 4, 9),
                            HeadCircumference = 34.4m,
                            Height = 58.3m,
                            PregnancyId = 1,
                            Weight = 6.6m
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2023, 4, 16),
                            HeadCircumference = 34.9m,
                            Height = 59.0m,
                            PregnancyId = 1,
                            Weight = 6.9m
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2023, 4, 23),
                            HeadCircumference = 35.3m,
                            Height = 60.2m,
                            PregnancyId = 1,
                            Weight = 7.1m
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2023, 4, 30),
                            HeadCircumference = 35.8m,
                            Height = 61.0m,
                            PregnancyId = 1,
                            Weight = 7.4m
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2023, 5, 7),
                            HeadCircumference = 36.2m,
                            Height = 62.5m,
                            PregnancyId = 1,
                            Weight = 7.7m
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2023, 5, 14),
                            HeadCircumference = 36.7m,
                            Height = 62.5m,
                            PregnancyId = 1,
                            Weight = 7.5m
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2023, 5, 21),
                            HeadCircumference = 38.0m,
                            Height = 65.0m,
                            PregnancyId = 1,
                            Weight = 7.0m
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2023, 5, 28),
                            HeadCircumference = 38.5m,
                            Height = 66.0m,
                            PregnancyId = 1,
                            Weight = 7.2m
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2023, 6, 4),
                            HeadCircumference = 39.0m,
                            Height = 67.0m,
                            PregnancyId = 1,
                            Weight = 7.4m
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2023, 6, 11),
                            HeadCircumference = 39.5m,
                            Height = 68.0m,
                            PregnancyId = 1,
                            Weight = 7.6m
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2023, 6, 18),
                            HeadCircumference = 40.0m,
                            Height = 69.0m,
                            PregnancyId = 1,
                            Weight = 7.8m
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2023, 6, 25),
                            HeadCircumference = 40.5m,
                            Height = 70.0m,
                            PregnancyId = 1,
                            Weight = 8.0m
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2023, 7, 2),
                            HeadCircumference = 41.0m,
                            Height = 71.0m,
                            PregnancyId = 1,
                            Weight = 8.2m
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2023, 7, 9),
                            HeadCircumference = 41.5m,
                            Height = 72.0m,
                            PregnancyId = 1,
                            Weight = 8.4m
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateOnly(2023, 7, 16),
                            HeadCircumference = 42.0m,
                            Height = 73.0m,
                            PregnancyId = 1,
                            Weight = 8.6m
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateOnly(2023, 7, 23),
                            HeadCircumference = 42.5m,
                            Height = 74.0m,
                            PregnancyId = 1,
                            Weight = 8.8m
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateOnly(2023, 7, 30),
                            HeadCircumference = 43.1m,
                            Height = 75.2m,
                            PregnancyId = 1,
                            Weight = 9.1m
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateOnly(2023, 8, 6),
                            HeadCircumference = 43.6m,
                            Height = 76.5m,
                            PregnancyId = 1,
                            Weight = 9.3m
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateOnly(2023, 8, 13),
                            HeadCircumference = 44.2m,
                            Height = 77.3m,
                            PregnancyId = 1,
                            Weight = 9.5m
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateOnly(2023, 8, 20),
                            HeadCircumference = 44.7m,
                            Height = 78.1m,
                            PregnancyId = 1,
                            Weight = 9.7m
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateOnly(2023, 8, 27),
                            HeadCircumference = 45.3m,
                            Height = 79.4m,
                            PregnancyId = 1,
                            Weight = 9.9m
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateOnly(2023, 9, 3),
                            HeadCircumference = 45.8m,
                            Height = 80.2m,
                            PregnancyId = 1,
                            Weight = 10.1m
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateOnly(2023, 9, 10),
                            HeadCircumference = 46.4m,
                            Height = 81.5m,
                            PregnancyId = 1,
                            Weight = 10.4m
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateOnly(2023, 9, 17),
                            HeadCircumference = 46.9m,
                            Height = 82.3m,
                            PregnancyId = 1,
                            Weight = 10.6m
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateOnly(2023, 9, 24),
                            HeadCircumference = 47.3m,
                            Height = 83.7m,
                            PregnancyId = 1,
                            Weight = 10.7m
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateOnly(2023, 10, 1),
                            HeadCircumference = 47.8m,
                            Height = 84.5m,
                            PregnancyId = 1,
                            Weight = 10.9m
                        });
                });

            modelBuilder.Entity("DAL.Entities.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PregnancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PregnancyId");

                    b.ToTable("Milestones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2023, 1, 1),
                            Descriptions = "First Trimester",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2023, 1, 15),
                            Descriptions = "First Doctor Visit",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2023, 4, 1),
                            Descriptions = "Second Trimester",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2023, 5, 1),
                            Descriptions = "Baby's First Kick",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2023, 6, 1),
                            Descriptions = "Gender Reveal",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2023, 7, 1),
                            Descriptions = "Third Trimester",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2023, 8, 1),
                            Descriptions = "Ultrasound Checkup",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2023, 8, 15),
                            Descriptions = "Baby Shower",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2023, 9, 15),
                            Descriptions = "Final Doctor Visit",
                            PregnancyId = 1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2023, 10, 1),
                            Descriptions = "Due Date",
                            PregnancyId = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.Pregnancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ConceptionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pregnancies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConceptionDate = new DateOnly(2023, 1, 1),
                            DueDate = new DateOnly(2023, 10, 1),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ConceptionDate = new DateOnly(2024, 1, 1),
                            DueDate = new DateOnly(2024, 9, 25),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Name = "Admin",
                            Password = "Admin@123",
                            Phone = "0905123000",
                            isActive = true,
                            isAdmin = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "active.user@example.com",
                            Name = "Elizabeth Taylor",
                            Password = "ActiveUser@123",
                            Phone = "0905123001",
                            isActive = true,
                            isAdmin = false
                        },
                        new
                        {
                            Id = 3,
                            Email = "inactive.user@example.com",
                            Name = "Victoria Beckham",
                            Password = "InactiveUser@123",
                            Phone = "0905123002",
                            isActive = false,
                            isAdmin = false
                        });
                });

            modelBuilder.Entity("DAL.Entities.FetusData", b =>
                {
                    b.HasOne("DAL.Entities.Pregnancy", "Pregnancy")
                        .WithMany("FetusDatas")
                        .HasForeignKey("PregnancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregnancy");
                });

            modelBuilder.Entity("DAL.Entities.Milestone", b =>
                {
                    b.HasOne("DAL.Entities.Pregnancy", "Pregnancy")
                        .WithMany("Milestones")
                        .HasForeignKey("PregnancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregnancy");
                });

            modelBuilder.Entity("DAL.Entities.Pregnancy", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Pregnancies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Pregnancy", b =>
                {
                    b.Navigation("FetusDatas");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("Pregnancies");
                });
#pragma warning restore 612, 618
        }
    }
}
